### ISSUE TITLE
Changing tray icon not working

### ISSUE THREAD

**Issue by malaupa** [knightpp/sni#6]
Changing icon using:
```
tray.SetIconName("emblem-mail")
tray.SignalNewIcon()
```
is not working.

I tried the example in https://github.com/knightpp/sni/blob/main/examples/simple/main.go and I remove the comments from https://github.com/knightpp/sni/blob/main/examples/simple/main.go#L40-L60 -> nothing happens.

I tested the example under Ubuntu 22.04.

**Comment by knightpp** [comment]
I've spent some time looking into it, but I couldn't fix. It seems the lib needs a rewrite to allow dynamically changing properties. PRs are welcome.

**Comment by malaupa** [comment]
Today I discovered https://github.com/slytomcat/systray which solves completely my need. Sorry for the ticket. I will closed it.
